export default {
  SET_ACTIVE_WORKSPACE: 'SET_ACTIVE_WORKSPACE',
  SET_ACTIVE_WORKSPACE_PROJECT_ID: 'SET_ACTIVE_WORKSPACE_PROJECT_ID',
  SET_ACTIVE_WORKSPACE_STATUS: 'SET_ACTIVE_WORKSPACE_STATUS',
  SET_ACTIVE_WORKSPACE_SUB_STATUS: 'SET_ACTIVE_WORKSPACE_SUB_STATUS',
  CLEAR_ACTIVE_WORKSPACE: 'CLEAR_ACTIVE_WORKSPACE',
  SET_WORKSPACE_USERS: 'SET_WORKSPACE_USERS',
  SET_HAS_NOTIFICATION: 'SET_HAS_NOTIFICATION',
  SET_TRIAL_END: 'SET_TRIAL_END',
  SET_PERIOD_END: 'SET_PERIOD_END'
};

export type ActiveWorkspace = any | null;
export type WorkspaceStore = {
  activeWorkspace: ActiveWorkspace;
  trialEnd: number;
  periodEnd: number;
  workspaceUsers: any;
  hasNotification: boolean;
};
